// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: v1/get-shopping-list-link.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShoppingListLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShoppingListId string `protobuf:"bytes,1,opt,name=shoppingListId,proto3" json:"shoppingListId,omitempty"`
	RequesterId    string `protobuf:"bytes,2,opt,name=requesterId,proto3" json:"requesterId,omitempty"`
	LinkPattern    string `protobuf:"bytes,3,opt,name=linkPattern,proto3" json:"linkPattern,omitempty"`
}

func (x *GetShoppingListLinkRequest) Reset() {
	*x = GetShoppingListLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_get_shopping_list_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShoppingListLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShoppingListLinkRequest) ProtoMessage() {}

func (x *GetShoppingListLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_shopping_list_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShoppingListLinkRequest.ProtoReflect.Descriptor instead.
func (*GetShoppingListLinkRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_shopping_list_link_proto_rawDescGZIP(), []int{0}
}

func (x *GetShoppingListLinkRequest) GetShoppingListId() string {
	if x != nil {
		return x.ShoppingListId
	}
	return ""
}

func (x *GetShoppingListLinkRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *GetShoppingListLinkRequest) GetLinkPattern() string {
	if x != nil {
		return x.LinkPattern
	}
	return ""
}

type GetShoppingListLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link      string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
}

func (x *GetShoppingListLinkResponse) Reset() {
	*x = GetShoppingListLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_get_shopping_list_link_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShoppingListLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShoppingListLinkResponse) ProtoMessage() {}

func (x *GetShoppingListLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_shopping_list_link_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShoppingListLinkResponse.ProtoReflect.Descriptor instead.
func (*GetShoppingListLinkResponse) Descriptor() ([]byte, []int) {
	return file_v1_get_shopping_list_link_proto_rawDescGZIP(), []int{1}
}

func (x *GetShoppingListLinkResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *GetShoppingListLinkResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_v1_get_shopping_list_link_proto protoreflect.FileDescriptor

var file_v1_get_shopping_list_link_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x2d, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2d, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x68,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73,
	0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x6c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72,
	0x6e, 0x22, 0x6b, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x42, 0x44,
	0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x70,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x6c, 0x69, 0x65, 0x2f, 0x63, 0x68, 0x65, 0x66, 0x62, 0x6f, 0x6f,
	0x6b, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_get_shopping_list_link_proto_rawDescOnce sync.Once
	file_v1_get_shopping_list_link_proto_rawDescData = file_v1_get_shopping_list_link_proto_rawDesc
)

func file_v1_get_shopping_list_link_proto_rawDescGZIP() []byte {
	file_v1_get_shopping_list_link_proto_rawDescOnce.Do(func() {
		file_v1_get_shopping_list_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_get_shopping_list_link_proto_rawDescData)
	})
	return file_v1_get_shopping_list_link_proto_rawDescData
}

var file_v1_get_shopping_list_link_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_get_shopping_list_link_proto_goTypes = []interface{}{
	(*GetShoppingListLinkRequest)(nil),  // 0: v1.GetShoppingListLinkRequest
	(*GetShoppingListLinkResponse)(nil), // 1: v1.GetShoppingListLinkResponse
	(*timestamppb.Timestamp)(nil),       // 2: google.protobuf.Timestamp
}
var file_v1_get_shopping_list_link_proto_depIdxs = []int32{
	2, // 0: v1.GetShoppingListLinkResponse.expiresAt:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_get_shopping_list_link_proto_init() }
func file_v1_get_shopping_list_link_proto_init() {
	if File_v1_get_shopping_list_link_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_get_shopping_list_link_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShoppingListLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_get_shopping_list_link_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShoppingListLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_get_shopping_list_link_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_get_shopping_list_link_proto_goTypes,
		DependencyIndexes: file_v1_get_shopping_list_link_proto_depIdxs,
		MessageInfos:      file_v1_get_shopping_list_link_proto_msgTypes,
	}.Build()
	File_v1_get_shopping_list_link_proto = out.File
	file_v1_get_shopping_list_link_proto_rawDesc = nil
	file_v1_get_shopping_list_link_proto_goTypes = nil
	file_v1_get_shopping_list_link_proto_depIdxs = nil
}
